import test from 'node:test';import assert from 'node:assert/strict';
import { GameController } from '../core/controller.mjs';
import { legalMoves } from '../core/game.mjs';
function setup() {const memory=new Map();let wall=1800000000000,mono=0;const c=new GameController({storage:{getItem:async k=>memory.get(k)??null,setItem:async(k,v)=>memory.set(k,v)},locale:'de-DE',now:()=>wall,monotonic:()=>mono});return{c,advance(ms){wall+=ms;mono+=ms;c.tick();}};}
test('controller initializes, starts, pauses and resumes a persisted attempt',async()=>{const{c}=setup();await c.initialize();assert.ok(c.getSnapshot().loaded);c.play();const board=c.getSnapshot().session.game.board;c.pause();assert.equal(c.getSnapshot().modal,'pause');c.resume();assert.equal(c.getSnapshot().modal,null);assert.deepEqual(c.getSnapshot().session.game.board,board);await c.flush();});
test('controller only consumes gift time during active gameplay',async()=>{const{c,advance}=setup();await c.initialize();c.activate('time10');advance(1000);assert.equal(c.getSnapshot().session.profile.unlimitedSeconds,600);c.play();advance(1000);assert.equal(c.getSnapshot().session.profile.unlimitedSeconds,599);c.pause();advance(1000);assert.equal(c.getSnapshot().session.profile.unlimitedSeconds,599);c.resume();c.setForeground(false);advance(100000);assert.equal(c.getSnapshot().session.profile.unlimitedSeconds,599);c.setForeground(true);advance(1000);assert.equal(c.getSnapshot().session.profile.unlimitedSeconds,599);});
test('reduced-motion move resolves immediately and repeated taps are locked out',async()=>{const{c}=setup();await c.initialize();c.preference('reducedMotion',true);c.play();const g=c.getSnapshot().session.game;const[a,b]=legalMoves(g)[0];await c.move(a,b);assert.equal(c.getSnapshot().session.game.moves,g.moves-1);assert.equal(c.getSnapshot().busy,false);await c.flush();});
test('navigation away from gameplay pauses active time without discarding the attempt',async()=>{const{c,advance}=setup();await c.initialize();c.activate('time10');c.play();c.navigate('home');advance(1000);assert.equal(c.getSnapshot().session.profile.unlimitedSeconds,600);assert.ok(c.getSnapshot().session.game);c.play();assert.equal(c.getSnapshot().screen,'game');});
test('activating time while an attempt exists protects that resumed attempt',async()=>{const{c}=setup();await c.initialize();c.play();assert.equal(c.getSnapshot().session.protectedAttempt,false);c.navigate('treasures');c.activate('time10');c.play();assert.equal(c.getSnapshot().session.protectedAttempt,true);c.abandon();assert.equal(c.getSnapshot().session.profile.lives,5);});
