import test from 'node:test';
import assert from 'node:assert/strict';
const module = await import('../core/voice-pool.mjs').catch(()=>({}));
function pool(adapter,options){assert.equal(typeof module.createVoicePool,'function','bounded voice pool exists');return module.createVoicePool(adapter,options);}
function adapter(){const active=new Set(),stops=[],starts=[];return {active,stops,starts,start:async(cue,guard)=>{if(guard.isCurrent()){active.add(cue);starts.push(cue);return true;}return false;},stop(cue){active.delete(cue);stops.push(cue);}};}
test('a fourth voice evicts the oldest; max three voices sound together',async()=>{const a=adapter(),p=pool(a);for(const cue of ['bomb','prism','rocket','win'])await p.play(cue);assert.deepEqual([...a.active],['prism','rocket','win']);assert.deepEqual(a.stops,['bomb']);p.dispose();});
test('repeated cues replace themselves rather than layering copies',async()=>{const a=adapter(),p=pool(a);await p.play('bomb');await p.play('bomb');assert.equal(a.active.size,1);assert.deepEqual(a.stops,['bomb']);});
test('stop invalidates a native seek or browser unlock still in flight',async()=>{let release;const played=[];const p=pool({start:async(cue,guard)=>{await new Promise(r=>release=r);if(guard.isCurrent()){played.push(cue);return true;}return false;},stop(){}});const pending=p.play('bomb');p.stop();release();assert.equal(await pending,false);assert.deepEqual(played,[]);});
test('voice capacity is reserved before asynchronous initialization finishes',async()=>{const releases=[],played=[],stops=[];const p=pool({start:async(cue,guard)=>{await new Promise(r=>releases.push(r));if(guard.isCurrent()){played.push(cue);return true;}return false;},stop(cue){stops.push(cue);}});const jobs=['bomb','rocket','prism','win'].map(c=>p.play(c));releases.forEach(r=>r());await Promise.all(jobs);assert.deepEqual(played,['rocket','prism','win']);assert.deepEqual(stops,['bomb']);});
test('failed and naturally ended voices free capacity; old onEnded cannot stop replacement',async()=>{const a=adapter(),ends=[];a.start=async(cue,guard)=>{if(cue==='broken')throw Error('device');ends.push(guard.onEnded);a.active.add(cue);return true;};const p=pool(a);assert.equal(await p.play('broken'),false);await p.play('bomb');await p.play('bomb');ends[0]();await p.play('prism');await p.play('win');assert.deepEqual(a.stops,['broken','bomb']);ends[1]();await p.play('rocket');assert.deepEqual(a.stops,['broken','bomb']);});
test('disposal is idempotent and late calls never reach released devices',async()=>{const a=adapter(),p=pool(a);await p.play('bomb');p.dispose();p.dispose();assert.equal(await p.play('win'),false);assert.equal(a.active.size,0);assert.deepEqual(a.starts,['bomb']);assert.throws(()=>pool(a,{maxVoices:0}),RangeError);});
