import {createFeedbackDriver} from '/core/feedback.mjs';
import {createBrowserAudio} from '/web/audio.mjs';
import {restorationFor} from '/core/restoration.mjs';
import {GameController} from '/core/controller.mjs';
import {WORLDS,levelFor} from '/core/levels.mjs';
import {goalProgress,starsFor} from '/core/game.mjs';
import {remainingLifeSeconds} from '/core/profile.mjs';
import {t,clock,SHAPES} from '/ui/strings.mjs';
import {domeSvg,boardSvg,gemSvg,uiIcon} from '/ui/art.mjs';
const c=new GameController({storage:{getItem:async k=>localStorage.getItem(k),setItem:async(k,v)=>localStorage.setItem(k,v)},locale:navigator.language});
const audio=createBrowserAudio(),soundDriver=createFeedbackDriver(audio);
const app=document.getElementById('app');let last=null,lastBoard='',down=null;
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const tx=(key,args)=>t(c.state.session.profile.language,key,args);
const action=(a,label,klass='primary',extra='')=>`<button class="${klass}" data-action="${a}" ${extra}>${label}</button>`;
const iconButton=(a,icon,label)=>action(a,uiIcon(icon),'icon-btn',`aria-label="${esc(label)}"`);
function completed(world) {return restorationFor(c.state.session.profile,world).completed;}
function restorationMarkup(world){const r=restorationFor(c.state.session.profile,world);return `<div class="restoration-card"><div class="progress-meta"><span>${tx(r.detail||'worldComplete')}</span><span>${tx('milestoneProgress',{n:r.stage})}</span></div><div class="milestone-track" aria-label="${tx('milestoneProgress',{n:r.stage})}">${[1,2,3,4,5].map(i=>`<i class="${i<=r.stage?'awake':''}"></i>`).join('')}</div></div>`;}
function stars(n,klass='level-stars') {return `<div class="${klass}">${[1,2,3].map(i=>uiIcon('star',i<=n?'#f7d58d':'#74988b')).join('')}</div>`;}
function header(){return `<header class="top"><div class="brand"><span class="brand-mark">${uiIcon('capsule','#d8d9b0')}</span>WUNDERKAPSELN</div><div class="top-right"><button class="life" data-action="treasures" aria-label="${tx('lives')}">${uiIcon('heart','#efa99f')}<span id="life-value"></span></button>${iconButton('settings','settings',tx('settings'))}</div></header>`;}
function nav(){return `<nav class="tabs">${[['home','capsule','explore'],['atlas','atlas','atlas'],['treasures','gift','treasures']].map(([page,icon,key])=>action(page,`${uiIcon(icon,c.state.screen===page?'#f4d393':'#81a7a3')}<span>${tx(key)}</span>`,`tab ${c.state.screen===page?'active':''}`)).join('')}</nav>`;}
function home(){const s=c.state,p=s.session.profile,w=WORLDS[s.world],done=completed(s.world),resume=s.session.game?.status==='playing';const lines=tx('headline').split('\n');return `<section class="hero"><p class="eyebrow">${tx('tagline')}</p><h1>${esc(lines[0])}<br><span>${esc(lines[1])}</span></h1></section><div class="home-art" aria-label="${esc(w[p.language])}">${domeSvg(s.world,done/40)}</div><div class="world-info"><div><h2>${w[p.language]}</h2><div class="muted">${tx('restoration')}</div></div><span class="world-number">${tx('world')} ${String(s.world+1).padStart(2,'0')} / 12</span></div><div class="bar"><i style="width:${done/40*100}%"></i></div><div class="progress-meta"><span>${done===40?tx('worldComplete'):tx('nextDetail',{n:restorationFor(p,s.world).remaining})}</span><span>${done} / 40</span></div>${restorationMarkup(s.world)}${action('play',`${uiIcon('play','#3d5547')}<span>${tx(resume?'resume':'play')}<span class="small">${tx('level')} ${resume?s.session.game.levelId:p.unlocked}</span></span>`)}<p class="home-foot">${tx('offline')} &nbsp; / &nbsp; ${tx('alpha')}</p>`;}
function atlas(){const p=c.state.session.profile;return `<p class="eyebrow">WUNDERKAPSELN</p><h1 class="page-title">${tx('allWorlds')}</h1><p class="intro">${tx('atlasIntro')}</p><div class="atlas-grid">${WORLDS.map((w,i)=>`<button class="world-card ${p.unlocked<i*40+1?'locked':''}" data-action="world" data-id="${i}"><div class="mini-label">${tx('world')} ${String(i+1).padStart(2,'0')}</div><div class="art">${domeSvg(i,completed(i)/40)}</div><h3>${w[p.language]}</h3><div class="muted">${p.unlocked<i*40+1?tx('unlocks',{n:i*40+1}):`${completed(i)} / 40 ${tx('level')}`}</div></button>`).join('')}</div>`;}
function levels(){const s=c.state,p=s.session.profile;return `<div class="game-top">${iconButton('atlas','back',tx('atlas'))}<span class="eyebrow">${tx('world')} ${s.world+1}</span><span></span></div><div class="section-art">${domeSvg(s.world,completed(s.world)/40)}</div><h1 class="page-title center">${WORLDS[s.world][p.language]}</h1>${restorationMarkup(s.world)}<p class="intro center">${tx('chooseLevel')}</p><div class="level-grid">${Array.from({length:40},(_,j)=>{const id=s.world*40+j+1,n=p.stars[id]||0;return action('level',`${id}${stars(n)}`,`level-node ${n?'done':id===p.unlocked?'current':''}`,`data-id="${id}" ${id>p.unlocked?'disabled':''} aria-label="${tx('level')} ${id}, ${n}/3"`);}).join('')}</div>`;}
function game(){const s=c.state,g=s.session.game,w=WORLDS[g.world];return `<div class="game-top">${iconButton('home','back',tx('backWorld'))}<div class="game-level"><p class="eyebrow">${w[s.session.profile.language]}</p><h1>${tx('level')} ${g.levelId}</h1></div>${iconButton('pause','pause',tx('pause'))}</div><div class="game-banner"><div class="game-banner-art">${domeSvg(g.world,completed(g.world)/40)}</div><div class="game-banner-copy">${tx(g.levelId<=3?'tutorial':w.wonder+'Help')}</div></div><div class="objectives"><div class="moves-box"><strong id="moves">${g.moves}</strong><small>${tx('moves')}</small></div><div class="goal-box" id="goals"></div></div><div id="board" class="board-wrap"><div class="board-art" id="board-art"></div><div class="hits" role="group" aria-label="${tx('goals')}">${g.board.map((_,i)=>`<button class="cell" data-hit="${i}" aria-label="${tx('cell',{r:Math.floor(i/8)+1,c:i%8+1})}"></button>`).join('')}</div></div><div class="board-caption" id="caption" aria-live="polite"></div><div class="wonder-row"><button data-action="wonder" class="wonder" id="wonder"></button>${action('hint',`${uiIcon('hint')}<span>${tx('hint')}</span>`,'hint')}</div><p class="game-help">${tx('rulesBody')}</p>${action('rules',tx('rules'),'text-btn')}</div>`;}
function ownedPacks(){const p=c.state.session.profile;return [['lives5','packLives'],['time60','packHour'],['time240','packFour']].filter(([key])=>p.inventory[key]>0).map(([key,label])=>`<div class="card owned-pack"><p class="eyebrow">${tx('ownedPacks')}</p><h3>${tx(label)}</h3><p>${tx('packCount',{n:p.inventory[key]})}</p>${action('activate',tx('activate'),'primary',`data-key="${key}"`)}</div>`).join('');}
function treasures(){const p=c.state.session.profile;return `<p class="eyebrow">${tx('treasures')}</p><h1 class="page-title">${tx('inventory')}</h1><div class="card"><div class="gift-art">${uiIcon('gift','#f2d397')}</div><h3>${tx('gift')}</h3><p>${tx('giftBody')}</p>${action('activate',tx(p.inventory.time10?'activate':'giftUsed'),'primary',`data-key="time10" ${p.inventory.time10?'':'disabled'}`)}</div><div class="card reserve-card"><h3>${tx('reserveLives')}</h3><div class="time-big" id="reserve-value">${p.reserveLives}</div><p>${tx('reserveBody')}</p></div>${ownedPacks()}<div class="card"><h3>${tx('activeTime')}</h3><div class="time-big" id="time-value">${clock(p.unlimitedSeconds)}</div><p>${tx('timeRule')}</p></div><div class="card"><h3>${tx('futureShop')}</h3>${[['heart','packLives'],['star','packHour'],['star','packFour']].map(([icon,key])=>`<div class="shop-row"><span class="shop-icon">${uiIcon(icon,'#b1cabc')}</span><div><strong>${tx(key)}</strong><small>${tx('notAvailable')}</small></div></div>`).join('')}<p style="margin-top:12px;margin-bottom:0">${tx('shopNotice')}</p></div>`;}
function settings(){const p=c.state.session.profile;return `<p class="eyebrow">WUNDERKAPSELN</p><h1 class="page-title">${tx('settings')}</h1><div class="card"><h3>${tx('language')}</h3><div class="language">${['de','en'].map(lang=>action('language',lang==='de'?'Deutsch':'English',`chip ${p.language===lang?'active':''}`,`data-value="${lang}"`)).join('')}</div>${['sound','reducedMotion','haptics'].map(key=>`<div class="settings-row"><span>${tx(key==='reducedMotion'?'motion':key)}</span><button role="switch" aria-checked="${p[key]}" aria-label="${tx(key==='reducedMotion'?'motion':key)}" data-action="preference" data-key="${key}" class="toggle ${p[key]?'on':''}"><i></i></button></div>`).join('')}</div><div class="card"><h3>${tx('offline')}</h3><p>${tx('localPrivacy')}</p></div><p class="version">${tx('alpha')} / KAMILUNAVO</p>`;}
function modal(){const s=c.state,g=s.session.game;let content='';
  if(s.modal==='result'){const won=g.status==='won';content=`${won?stars(starsFor(g),'result-stars'):uiIcon('heart','#eab7a2',40)}<h2>${tx(won?'won':'lost')}</h2><p>${tx(won?'wonBody':s.session.protectedAttempt?'protectedBody':'lostBody')}</p>${won&&s.milestone?`<div class="milestone-celebration"><p class="eyebrow">${tx('milestoneWon')}</p><h3>${tx(s.milestone.detail)}</h3></div>`:''}${won?`<div class="result-art">${domeSvg(g.world,completed(g.world)/40)}</div>`:''}${action(won?'next':'retry',tx(won?(g.levelId===480?'campaignWon':'next'):'retry'))}${action('home',tx('backWorld'),'text-btn')}`;}
  if(s.modal==='pause') content=`<h2>${tx('pause')}</h2><p>${tx('pauseBody')}</p>${action('resume',tx('resume'))}${action('requestAbandon',tx('abandon'),'secondary')}`;
  if(s.modal==='abandon') content=`<h2>${tx('abandonTitle')}</h2><p>${tx(s.session.protectedAttempt?'protectedBody':'abandonBody')}</p>${action('resume',tx('resume'))}${action('abandon',tx('confirm'),'secondary')}`;
  if(s.modal==='noLives') content=`<h2>${tx('noLives')}</h2><p>${tx('noLivesBody')}</p><span class="muted">${tx('nextLife')}</span><div class="time-big" id="life-countdown">${clock(remainingLifeSeconds(s.session.profile))}</div>${action('treasures',tx('treasures'))}${action('close',tx('close'),'text-btn')}`;
  if(s.modal==='rules') content=`<h2>${tx('rules')}</h2><p>${tx('rulesBody')}</p><h3>${tx(WORLDS[s.world].wonder)}</h3><p>${tx(WORLDS[s.world].wonder+'Help')}</p>${action('close',tx('close'))}`;
  return s.modal?`<div class="overlay"><section class="dialog" role="dialog" aria-modal="true" aria-label="${tx('level')}">${content}</section></div>`:'';
}
function render(){const s=c.state,p=s.session.profile;
  if(!s.loaded){
    document.documentElement.lang=p.language;
    if(!last||last.loaded||last.loadError!==s.loadError){
      app.innerHTML=`<main class="content"><p class="eyebrow">WUNDERKAPSELN</p>${s.loadError?`<section class="card save-protection" role="alert"><div class="gift-art">${uiIcon('capsule','#f2d397')}</div><h1 class="page-title">${tx('saveTitle')}</h1><p>${tx(s.loadError)}</p><p>${tx('saveProtected')}</p>${action('initialize',tx('loadRetry'))}</section>`:`<p role="status">${tx('loading')}</p>`}</main>`;
      bind();
    }
    last=s;return;
  }
  document.documentElement.lang=p.language;app.classList.toggle('reduce',c.motionReduced());
  const full=!last||!last.loaded||last.saveError!==s.saveError||(['corrupt','recovered','packCapacity','notAvailable'].includes(s.notice)&&last.notice!==s.notice)||last.screen!==s.screen||last.modal!==s.modal||last.world!==s.world||last.session.profile.language!==p.language||((s.screen!=='game')&&(last.session.profile.unlocked!==p.unlocked||last.session.profile.reserveLives!==p.reserveLives||JSON.stringify(last.session.profile.inventory)!==JSON.stringify(p.inventory)||last.session.profile.reducedMotion!==p.reducedMotion||last.session.profile.haptics!==p.haptics||last.session.profile.sound!==p.sound));
  if(full){const pages={home,atlas,levels,game,treasures,settings};app.innerHTML=header()+`<main class="content ${s.screen==='game'?'game-content':''}">${s.saveError||['corrupt','recovered','packCapacity','notAvailable'].includes(s.notice)?`<div class="notice" role="alert">${tx(s.saveError?'saveError':s.notice)}</div>`:''}${pages[s.screen]()}</main>`+(s.screen==='game'?'':nav())+modal();lastBoard='';bind();if(s.modal)app.querySelector('.dialog button')?.focus();}
  const life=document.getElementById('life-value');if(life){life.textContent=(p.unlimitedSeconds>0?clock(p.unlimitedSeconds):`${p.lives} / 5`)+(p.reserveLives>0?` +${p.reserveLives}`:'');life.parentElement.setAttribute('aria-label',`${p.lives} ${tx('lives')}, ${tx('reserveCount',{n:p.reserveLives})}`);}
  for(const[id,value]of [['reserve-value',String(p.reserveLives)],['time-value',clock(p.unlimitedSeconds)],['life-countdown',clock(remainingLifeSeconds(p))]]){const el=document.getElementById(id);if(el)el.textContent=value;}
  if(s.screen==='game')updateGame();last=s;
}
function updateGame(){const s=c.state,g=s.session.game,d=s.visual||g;document.getElementById('moves').textContent=g.moves;
  document.getElementById('goals').innerHTML=g.targets.map(target=>{const value=goalProgress(g,target);return `<div class="goal ${value===target.amount?'done':''}" aria-label="${esc(target.kind==='frost'?tx('frostGoal',{n:target.amount-value}):tx('collect',{n:target.amount-value,shape:tx(SHAPES[target.color])}))}">${target.kind==='frost'?uiIcon('frost','#b8eaf2'):gemSvg({color:target.color,special:''})}<strong>${value===target.amount?uiIcon('check','#c2e4b0',20):`${value}/${target.amount}`}</strong></div>`;}).join('');
  const art=boardSvg(d,{selected:s.selected,hint:s.hint,...s.animation});if(art!==lastBoard){document.getElementById('board-art').innerHTML=art;lastBoard=art;}
  document.getElementById('board').classList.toggle('busy',s.busy);
  document.querySelectorAll('[data-hit]').forEach(el=>{const i=Number(el.dataset.hit),cell=g.board[i];el.setAttribute('aria-label',`${tx('cell',{r:Math.floor(i/8)+1,c:i%8+1})}: ${tx(cell.special||SHAPES[cell.color])}${g.frost[i]?`, ${tx('frost')}`:''}`);});
  const ready=g.charge>=100&&!g.wonderUsed,wonder=document.getElementById('wonder');wonder.disabled=!ready||s.busy;wonder.classList.toggle('charged',ready);wonder.innerHTML=`<span class="meter" style="width:${g.charge}%"></span>${uiIcon('star',ready?'#37584d':'#d7d6ad')}<strong>${tx(g.wonderUsed?'wonderUsed':'wonder')}<small>${tx(ready?'wonderReady':'wonderCharge')} ${ready||g.wonderUsed?'':`${g.charge}%`}</small></strong>`;
  document.getElementById('caption').textContent=s.wonder?tx('wonderSelect'):s.notice?tx(s.notice):s.session.protectedAttempt?tx('protected'):'';
}
function bind(){for(const el of app.querySelectorAll('[data-action]'))el.addEventListener('click',()=>{const a=el.dataset.action;
  if(['home','atlas','treasures','settings'].includes(a))c.navigate(a);
  else if(a==='world')c.world(Number(el.dataset.id));else if(a==='level')c.play(Number(el.dataset.id));
  else if(a==='activate')c.activate(el.dataset.key);else if(a==='language')c.preference('language',el.dataset.value);
  else if(a==='preference')c.preference(el.dataset.key,!c.state.session.profile[el.dataset.key]);
  else if(a==='rules')c.rules();else if(a==='close')c.closeModal();else if(typeof c[a]==='function')c[a]();
});
  for(const el of app.querySelectorAll('[data-hit]'))el.addEventListener('click',e=>{if(e.detail===0)c.tap(Number(el.dataset.hit));});
}
app.addEventListener('pointerdown',e=>{if(c.state.session.profile.sound)void audio.unlock().catch(()=>{});const el=e.target.closest('[data-hit]');if(!el)return;down={i:Number(el.dataset.hit),x:e.clientX,y:e.clientY};e.preventDefault();});
window.addEventListener('pointerup',e=>{if(!down)return;const d=down;down=null;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.max(Math.abs(dx),Math.abs(dy))>18){const target=d.i+(Math.abs(dx)>Math.abs(dy)?Math.sign(dx):Math.sign(dy)*8);c.move(d.i,target);}else c.tap(d.i);});
window.addEventListener('pointercancel',()=>{down=null;});
document.addEventListener('visibilitychange',()=>c.setForeground(!document.hidden));
window.addEventListener('pagehide',()=>c.setForeground(false));
window.addEventListener('keydown',e=>{if(c.state.session.profile.sound&&(e.key==='Enter'||e.key===' '))void audio.unlock().catch(()=>{});if(e.key==='Escape')c.back();if(e.key==='Tab'&&c.state.modal){const nodes=[...app.querySelectorAll('.dialog button:not(:disabled)')];const first=nodes[0],end=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end.focus();}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first.focus();}}});
const media=window.matchMedia('(prefers-reduced-motion: reduce)');
c.setSystemReducedMotion(media.matches);media.addEventListener('change',e=>c.setSystemReducedMotion(e.matches));
c.subscribe(()=>{render();void soundDriver.update(c.getSnapshot(),c.foreground);});
await c.initialize();setInterval(()=>c.tick(),250);
